version: "3.8"
# default-logging
x-logging:
  &default-logging
  options:
    max-size: "300m"
    max-file: "1"
  driver: json-file
# services
services:
  # nginx
  nginx:
    image: nginx:1.21.3
    container_name: nginx
    logging: *default-logging
    env_file:
      - common.env
    networks:
      - tax_preference_network
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/conf.d:/etc/nginx/conf.d
      - ${PWD}/nginx/web:/opt/web
  # mysql
  mysql:
    image: mysql:5.7
    container_name: mysql
    logging: *default-logging
    env_file:
      - common.env
    networks:
      - tax_preference_network
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/mysql/data:/var/lib/mysql
      - ${PWD}/mysql/conf:/etc/mysql/mysql.conf.d
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone='+8:00'
  # redis
  redis:
    image: redis:6.2.6
    container_name: redis
    logging: *default-logging
    env_file:
      - common.env
    networks:
      - tax_preference_network
    ports:
      - "6379:6379"
    volumes:
      - ${PWD}/redis/redis.conf:/etc/redis/redis.conf
      - ${PWD}/redis/data:/data
    command: redis-server /etc/redis/redis.conf --appendonly yes
  # minio
  minio:
    image: minio/minio
    container_name: minio
    logging: *default-logging
    env_file:
      - common.env
    networks:
      - tax_preference_network
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${PWD}/minio:/data
    environment:
      - "MINIO_ROOT_USER=root"
      - "MINIO_ROOT_PASSWORD=hcfAI123456"
    command: server /data --console-address ":9001"

networks:
  tax_preference_network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.13.0/24"