version: "3.8"
# default-logging
x-logging:
  &default-logging
  options:
    max-size: "300m"
    max-file: "1"
  driver: json-file
# services
services:
  # tax-preference-server
  tax-preference-server:
    image: hai-registry:5000/tax-preference-server:0.0.1
    container_name: tax-preference-server
    logging: *default-logging
    env_file:
      - common.env
      - server.env
    networks:
      - tax_preference_network
    ports:
      - "9090:9090"
      - "5090:5005"
  # tax-preference-web
  tax-preference-web:
    image: hai-registry:5000/tax-preference-web:0.0.1
    container_name: tax-preference-web
    logging: *default-logging
    env_file:
      - common.env
    networks:
      - tax_preference_network
    ports:
      - "3000:3000"

networks:
  tax_preference_network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.13.0/24"