# spring
spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://mysql:3306/tax_preference?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
    username: tax_preference
    password: ""
  # redis
  redis:
    host: redis
    port: 6379
    password: ""
    database: 0
  elasticsearch:
    rest:
      uris: http://elasticsearch:9200
  rabbitmq:
    host: rabbitmq
    virtual-host: tax_preference
    username: tax_preference
    password: ""

# swagger
springfox:
  documentation:
    enabled: false

## mybatis plus
#mybatis-plus:
#  configuration:
#    # print SQL
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# tax preference
tax-preference:
  # 数据库加密
  encrypt:
    key: "6b32c10d8ed53774"
  # 对象存储
  minio:
    endpoint: "http://minio:9000"
    bucket: "tax-preference"
    access-key: "tax_preference"
    secret-key: ""
  index:
    policies:
      index: policies_index_2022-01-04
      alias: policies
    policies-explain:
      index: policies_explain_index_2022-01-04
      alias: policies_explain
    frequently-asked-question:
      index: frequently_asked_question_index_2022-01-04
      alias: frequently_asked_question
    tax-preference:
      index: tax_preference_index_2022-01-04
      alias: tax_preference
    other-doc:
      index: other_doc_index_2022-01-04
      alias: other_doc
# 爬虫数据同步
spider-sync:
  enabled: false
  data-source:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://spider-db:3306/dataWEB?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
    username: ""
    password: ""
  minio:
    endpoint: "http://spider-minio:9000"
    bucket: "data-spider"
    access-key: "data_spider"
    secret-key: ""