# spring
spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://172.16.122.17:3306/tax_preference_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
    username: tax_preference
    password: tax_preference
  # redis
  redis:
    host: 172.16.122.17
    port: 6379
    password: foobared
    database: 2
  elasticsearch:
    rest:
      uris: http://172.16.122.17:9200
  rabbitmq:
    host: 172.16.122.17
    virtual-host: tax_preference_dev
    username: tax_preference_dev
    password: tax_preference_dev

# mybatis plus
mybatis-plus:
  configuration:
    # print SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# tax preference
tax-preference:
  # 数据库加密
  encrypt:
    key: "6b32c10d8ed53774"
  # 对象存储
  minio:
    endpoint: "http://172.16.122.17:9000"
    bucket: "tax-preference-dev"
    access-key: "tax_preference"
    secret-key: "tax_preference"
  index:
    policies:
      index: policies_index_2021-11-11_dev
      alias: policies_dev
    policies-explain:
      index: policies_explain_index_2021-11-17_dev
      alias: policies_explain_dev
    frequently-asked-question:
      index: frequently_asked_question_index_2021-11-17_dev
      alias: frequently_asked_question_dev
    tax-preference:
      index: tax_preference_index_2021-11-18_dev
      alias: tax_preference_dev
