# spring
spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://172.16.122.17:3306/tax_preference_dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
    username: tax_preference
    password: tax_preference
  # redis
  redis:
    host: 172.16.122.17
    port: 6379
    password: foobared
    database: 2
  elasticsearch:
    rest:
      uris: http://172.16.122.17:9200
  rabbitmq:
    host: 172.16.122.17
    virtual-host: tax_preference_dev
    username: tax_preference_dev
    password: tax_preference_dev
  mail:
    host: smtp.qq.com
    username: 1131375117@qq.com
    password: gulqeyfvrczhheac
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    ##         ssl:
    ##           enable :true
    default-encoding: utf-8
# swagger
springfox:
  documentation:
    enabled: true

# mybatis plus
mybatis-plus:
  configuration:
    # print SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# tax preference
tax-preference:
  # 数据库加密
  encrypt:
    key: "6b32c10d8ed53774"
  # 自动扫描并更新权限
  permission:
    scan-permission-and-save: false
  # 对象存储
  minio:
    endpoint: "http://172.16.122.17:9000"
    bucket: "tax-preference-dev"
    access-key: "tax_preference"
    secret-key: "tax_preference"
  index:
    policies:
      index: policies_index_2021-12-13_dev
      alias: policies_dev
    policies-explain:
      index: policies_explain_index_2021-12-13_dev
      alias: policies_explain_dev
    frequently-asked-question:
      index: frequently_asked_question_index_2021-12-13_dev
      alias: frequently_asked_question_dev
    tax-preference:
      index: tax_preference_index_2021-12-13_dev
      alias: tax_preference_dev
    other-doc:
      index: other_doc_index_2021-12-13_dev
      alias: other_doc_dev
    consultation:
      index: consultation_index_2022-02-17_dev
      alias: consultation_dev
# 爬虫数据同步
spider-sync:
  enabled: true
  data-source:
    driver-class-name: com.mysql.cj.jdbc.Driver
   # url: "jdbc:mysql://172.16.18.28:3306/dataWEB?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
   # username: "tencentcloud"
   # password: "oOSI-5QArNyH_rW9b--Xxbfax4k0"
    url: "jdbc:mysql://172.16.122.17:3306/dataWEB?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
    username: "tax_preference"
    password: "tax_preference"
  minio:
    endpoint: "http://172.16.18.28:9000"
    bucket: "data-spider"
    access-key: "data_spider"
    secret-key: "data_spider"

# 企业微信配置
wwx:
  # 税收优惠主应用
  tax-preference:
    corp-id: "wx9a124e5ac3e8815c"
    provider-secret: "-2siEGlPSyf5EeOk3g61TxgD9DwxazfF3MwQXFo9KygK6ijP9Rweh7IsXCGRQb9E"
    suite-id: "wx6028dadfd03632a8"
    secret: "2ZTaXIOLJ9oG_EzKsVtqRK-7ZSbwj_y9rIzdOXjKOq0"
    token: "Ey6liMxc2qvSt3ixoJCrRaVSOqrMPv"
    encoding-aes-key: "x1zyI2J87DSFvOByJ7XAXC2SD3mehcJFPDHrISBHmH6"
  # 税务小工具
  tax-tool:
    corp-id: "wx9a124e5ac3e8815c"
    provider-secret: "-2siEGlPSyf5EeOk3g61TxgD9DwxazfF3MwQXFo9KygK6ijP9Rweh7IsXCGRQb9E"
    suite-id: "wxe27c223ff88693e7"
    secret: "-cuNx4ZJOOsOWXDIdZMzS_-Bdt3EGKibNjLtYjVnCxI"
    token: "VzShwDoTtBMn9qahSB45nVQPqIY5Eh"
    encoding-aes-key: "gKUXxMtvyacfq3KczuhjJawW4IUpqV7CuLIIMWMPn5n"
  proxy:
    enable: true
    host: "1.117.164.184"
    port: 3200
    username: ""
    password: ""

# open-api
open-api:
  token-config:
    auto-renew: false
    is-share: false
