server:
  port: 9090
# spring
spring:
  profiles:
    active: stream,dev
  application:
    name: tax-preference-server
  # file upload
  servlet:
    multipart:
      max-request-size: 128MB
      max-file-size: 128MB

# swagger
swagger:
  docket:
    common:
      title: "公共服务接口"
      basePackage: cn.huacloud.taxpreference.controllers.common
    consumer:
      title: "前台接口"
      basePackage: cn.huacloud.taxpreference.controllers.consumer
    producer:
      title: "后台接口"
      basePackage: cn.huacloud.taxpreference.controllers.producer
    sso:
      title: "用户登录"
      basePackage: cn.huacloud.taxpreference.controllers.sso
    user:
      title: "用户管理"
      basePackage: cn.huacloud.taxpreference.controllers.user
    tool:
      title: "系统工具"
      basePackage: cn.huacloud.taxpreference.controllers.tool

# mybatis plus
mybatis-plus:
  global-config:
    banner: false
  configuration:
    call-setters-on-nulls: true
  type-enums-package: cn.huacloud.taxpreference.common.enums

# sa-token
sa-token:
  token-name: satoken
  activity-timeout: 14400
  is-share: true
  token-style: uuid
  is-log: true

logging:
  level:
    org.elasticsearch.client.RestClient: error