spring:
  cloud:
    function:
      definition: "savePoliciesSuppler;deletePoliciesSuppler;savePolicies;deletePolicies;savePoliciesExplainSuppler;deletePoliciesExplainSuppler;savePoliciesExplain;deletePoliciesExplain;saveFAQSuppler;deleteFAQSuppler;saveFAQ;deleteFAQ;saveTaxPreferenceSuppler;deleteTaxPreferenceSuppler;saveTaxPreference;deleteTaxPreference;saveOtherDocSuppler;deleteOtherDocSuppler;saveOtherDoc;deleteOtherDoc;saveConsultationSuppler;deleteConsultationSuppler;saveConsultation;deleteConsultation;sendSmsSuppler;sendSms;apiMonitorInfoSupplier;apiMonitorInfoConsumer"
      # 去除definition  saveApiUserStatisticsSuppler;updateApiUserStatisticsSuppler;saveApiUserStatistics;updateApiUserStatistics;saveUserMonitorInfoSuppler;saveUserMonitorInfo
    stream:
      bindings:
        # policies save
        savePoliciesSuppler-out-0:
          destination: savePoliciesExchange
        savePolicies-in-0:
          destination: savePoliciesExchange
          group: savePoliciesQueue
        # policies delete
        deletePoliciesSuppler-out-0:
          destination: deletePoliciesExchange
        deletePolicies-in-0:
          destination: deletePoliciesExchange
          group: deletePoliciesQueue
        # policies-explain save
        savePoliciesExplainSuppler-out-0:
          destination: savePoliciesExplainExchange
        savePoliciesExplain-in-0:
          destination: savePoliciesExplainExchange
          group: savePoliciesExplainQueue
        # policies-explain delete
        deletePoliciesExplainSuppler-out-0:
          destination: deletePoliciesExplainExchange
        deletePoliciesExplain-in-0:
          destination: deletePoliciesExplainExchange
          group: deletePoliciesExplainQueue
        # FAQ save
        saveFAQSuppler-out-0:
          destination: saveFAQExchange
        saveFAQ-in-0:
          destination: saveFAQExchange
          group: saveFAQQueue
        # FAQ delete
        deleteFAQSuppler-out-0:
          destination: deleteFAQExchange
        deleteFAQ-in-0:
          destination: deleteFAQExchange
          group: deleteFAQQueue
        # tax-preference save
        saveTaxPreferenceSuppler-out-0:
          destination: saveTaxPreferenceExchange
        saveTaxPreference-in-0:
          destination: saveTaxPreferenceExchange
          group: saveTaxPreferenceQueue
        # tax-preference delete
        deleteTaxPreferenceSuppler-out-0:
          destination: deleteTaxPreferenceExchange
        deleteTaxPreference-in-0:
          destination: deleteTaxPreferenceExchange
          group: deleteTaxPreferenceQueue
        # other-doc save
        saveOtherDocSuppler-out-0:
          destination: saveOtherDocExchange
        saveOtherDoc-in-0:
          destination: saveOtherDocExchange
          group: saveOtherDocQueue
        # other-doc delete
        deleteOtherDocSuppler-out-0:
          destination: deleteOtherDocExchange
        deleteOtherDoc-in-0:
          destination: deleteOtherDocExchange
          group: deleteOtherDocQueue
         #consultation save
        saveConsultationSuppler-out-0:
          destination: saveConsultationExchange
        saveConsultation-in-0:
          destination: saveConsultationExchange
          group: saveConsultationQueue
        # consultation delete
        deleteConsultationSuppler-out-0:
          destination: deleteConsultationExchange
        deleteConsultation-in-0:
          destination: deleteConsultationExchange
          group: deleteConsultationQueue
        #sms send
        sendSmsSuppler-out-0:
          destination: sendSmsExchange
        sendSms-in-0:
          destination: sendSmsExchange
          group: sendSmsQueue

        # api monitor info
        apiMonitorInfoSupplier-out-0:
          destination: apiMonitorInfoExchange
        apiMonitorInfoConsumer-in-0:
          destination: apiMonitorInfoExchange
          group: apiMonitorInfoQueue



