# spring
spring:
  # datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://172.16.122.17:3306/tax_preference_test?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
    username: tax_preference_test
    password: tax_preference_test
  # redis
  redis:
    host: 172.16.122.17
    port: 6379
    password: foobared
    database: 4
  elasticsearch:
    rest:
      uris: http://172.16.122.17:9200
  rabbitmq:
    host: 172.16.122.17
    virtual-host: tax_preference_test
    username: tax_preference_test
    password: tax_preference_test

# swagger
springfox:
  documentation:
    enabled: true

# mybatis plus
mybatis-plus:
  configuration:
    # print SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# tax preference
tax-preference:
  # 数据库加密
  encrypt:
    key: "6b32c10d8ed53774"
  # 对象存储
  minio:
    endpoint: "http://172.16.122.17:9000"
    bucket: "tax-preference-test"
    access-key: "tax_preference_test"
    secret-key: "tax_preference_test"
  index:
    policies:
      index: policies_index_2021-12-21_test
      alias: policies_test
    policies-explain:
      index: policies_explain_index_2021-12-21_test
      alias: policies_explain_test
    frequently-asked-question:
      index: frequently_asked_question_index_2021-12-21_test
      alias: frequently_asked_question_test
    tax-preference:
      index: tax_preference_index_22021-12-21_test
      alias: tax_preference_test
    other-doc:
      index: other_doc_index_2021-12-21_test
      alias: other_doc_test
# 爬虫数据同步
spider-sync:
  enabled: true
  data-source:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://172.16.18.28:3306/dataWEB?useUnicode=true&characterEncoding=UTF-8&useSSL=false"
    username: "tencentcloud"
    password: "oOSI-5QArNyH_rW9b--Xxbfax4k0"
  minio:
    endpoint: "http://172.16.18.28:9000"
    bucket: "data-spider"
    access-key: "data_spider"
    secret-key: "data_spider"