# server
server:
  port: 9090

# spring
spring:
  profiles:
    active: stream,dev
  application:
    name: tax-preference-server
  # file upload
  servlet:
    multipart:
      max-request-size: 128MB
      max-file-size: 128MB

# swagger
springfox:
  documentation:
    enabled: true

# mybatis plus
mybatis-plus:
  global-config:
    banner: false
  configuration:
    call-setters-on-nulls: true
  type-enums-package: cn.huacloud.taxpreference.common.enums

# sa-token
sa-token:
  token-name: satoken
  activity-timeout: 28800
  is-share: true
  token-style: uuid
  is-log: true
  is-print: false

# logging
logging:
  level:
    org.elasticsearch.client.RestClient: error
