# spring
spring:
  # datasource
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:sql/schema-h2.sql
    data: classpath:sql/data-h2.sql
    url: jdbc:h2:mem:tax-preference
    username: root
    password: test
  # redis
  redis:
    host: 172.16.122.17
    port: 6379
    password: foobared

# mybatis plus
mybatis-plus:
  configuration:
    # print SQL
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl